# Generated by Django 4.2.11 on 2025-07-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profissional',
            options={'permissions': (('detail_profissional', 'Pode ver detalhe do profissional '),)},
        ),
    ]
