# Generated by Django 5.2.3 on 2025-07-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='arquivo',
            field=models.FileField(default=1, upload_to='img'),
            preserve_default=False,
        ),
    ]
