# Generated by Django 5.2.3 on 2025-07-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='descricao',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
