# Generated by Django 5.2.3 on 2025-07-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0002_servico_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='categoria',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servico',
            name='tipo',
            field=models.TextField(max_length=100),
        ),
    ]
