# Generated by Django 5.2.3 on 2025-07-12 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0003_servico_categoria_alter_servico_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.TextField(max_length=100)),
                ('imagem', models.FileField(upload_to='imgServico')),
            ],
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='categoria',
            new_name='servico',
        ),
        migrations.AlterField(
            model_name='servico',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiposServicos', to='servico.tiposervico'),
        ),
    ]
