# Generated by Django 5.2.3 on 2025-07-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0004_tiposervico_rename_categoria_servico_servico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposervico',
            name='imagem',
            field=models.FileField(upload_to='img_servico'),
        ),
    ]
