# Generated by Django 4.2.11 on 2025-07-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={'permissions': (('detailhes_administrador', 'Pode ver detalhe do da view administrador'),)},
        ),
    ]
