# Generated by Django 5.2.3 on 2025-07-05 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('clinicaEstetica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
        ),
    ]
