# Generated by Django 4.2.11 on 2025-07-12 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preco')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servico.servico')),
            ],
        ),
    ]
