# Generated by Django 5.2.3 on 2025-07-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0001_initial'),
        ('servico', '0002_servico_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='servico',
        ),
        migrations.AddField(
            model_name='plano',
            name='servico',
            field=models.ManyToManyField(null=True, to='servico.servico'),
        ),
    ]
